# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Test
email: yeyingping26@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Good Good Study, Day Day Up!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  DiligentYe
rss: true

# Build settings
markdown: kramdown
theme: minima
    
date_format: "%Y-%m-%d"

plugins:
  - jekyll-feed

gitalk:
  enable: true #用来做启用判断可以不用 
  clientID: '4567a3c4249760e03c45' 
  clientSecret: 'ac62226f3a5245f0edb4e548af2f970490679e53' #同上 
  repo: 'DiligentYe.github.io' #仓库名称 
  owner: 'DiligentYe' #github用户名 
  admin: 'DiligentYe' 
  distractionFreeMode: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
